/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libjniSecante_JavaSecante */

#ifndef _Included_libjniSecante_JavaSecante
#define _Included_libjniSecante_JavaSecante
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libjniSecante_JavaSecante
 * Method:    ejecutarSecante
 * Signature: (IDDID)V
 */
JNIEXPORT void JNICALL Java_libjniSecante_JavaSecante_ejecutarSecante
  (JNIEnv *, jobject, jint, jdouble, jdouble, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
